crud_ajax/config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  resources :todos 
  devise_for :users, :path => '',
                     :path_names => {:sign_in => 'login', :sign_out => 'logout'}

end

crud_ajax/app/models/todo.rb
class Todo < ActiveRecord::Base

end

crud_ajax/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

crud_ajax/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

crud_ajax/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

crud_ajax/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def create
    todo = Todo.create(todo_params)
    render json: todo.to_json
  end
  def todo_params
    params.require(:todo).permit(:task)
  end
end

crud_ajax/app/helpers/application_helper.rb
module ApplicationHelper
end

crud_ajax/app/helpers/dashboard_helper.rb
module DashboardHelper
end

crud_ajax/app/helpers/todos_helper.rb
module TodosHelper
end

crud_ajax/app/views/dashboard/index.html.erb
<div class="container">
  <a class="waves-effect waves-light btn modal-trigger" href="#modal1"%>
    Add Todo
  </a>

<h1>Dashboard</h1>
<% if Todo.count > 0 %>
  <table class="highlight">
    <thead>
      <tr>
        <th>Done</th>
        <th>Priority</th>
        <th>Task</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% Todo.all.each do |todo| %>
        <tr>
          <td><%= todo.done %></td>
          <td><%= todo.priority %></td>
          <td><%= todo.task %></td>

            <td><%= button_to 'Delete',todo_path(todo), data: { confirm: "Are you sure?" }, class: 'btn btn-default delete', form: {id: todo.id}, method: :delete%></td>

        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
</div>

<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <%= form_for :todo do |f| %>
      <div class="input-field">
        <%= f.text_field :task, placeholder: "Task name" %>
      </div>
      <%= f.submit "Save todo", class: "waves-effect waves-light btn" %>
    <% end %>
  </div>
</div>

crud_ajax/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudAjax</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul>
    </div>
  </nav>
<% end %>
<%= yield %>

</body>
</html>